baseURL = 'https://ilia.moe/cool-stuff/recipes'
languageCode = 'en-us'
title = 'Recipes'
theme = 'waltuh-hugo-theme'

[taxonomies]
tag = 'tags'

[markup]
[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true
